apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observation-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: observation
    server: 'https://kubernetes.default.svc'
  source:
    chart: 'loki'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.5.0
    helm:
      version: v3
      releaseName: loki
      values: |
        replicas: 1
        persistence:
          enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
