apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - type: helm
      url: https://kubernetes.github.io/autoscaler/
      name: autoscaler
    - type: helm
      url: https://dapr.github.io/helm-charts/
      name: dapr.io
    - type: helm
      url: https://prometheus-community.github.io/helm-charts/
      name: prometheus-community
    - url: https://github.com/nautible/nautible-infra
      name: nautible-infra
    - url: https://github.com/nautible/nautible-plugin
      name: nautible-plugin
    - url: https://github.com/nautible/nautible-ms-app-product-manifest
      name: nautible-ms-app-product-manifest
    - url: https://github.com/nautible/nautible-ms-app-customer-manifest
      name: nautible-ms-app-customer-manifest
    - url: https://github.com/nautible/nautible-ms-app-stock-manifest
      name: nautible-ms-app-stock-manifest
    - url: https://github.com/nautible/nautible-ms-app-order-manifest
      name: nautible-ms-app-order-manifest
    - url: https://github.com/nautible/nautible-ms-app-payment-manifest
      name: nautible-ms-app-payment-manifest
