apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
patchesStrategicMerge:
  - external-secrets/application.yaml
resources:
  - metrics-server/application.yaml
  - autoscaler/application.yaml
